# Generated by Django 5.1.2 on 2024-10-18 00:14

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', banjo.models.StringField(default='')),
                ('categories', banjo.models.StringField(default='')),
                ('correct', banjo.models.BooleanField(default=False)),
                ('likes', banjo.models.IntegerField(default=0)),
                ('prompt', banjo.models.StringField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
