# Generated by Django 5.1.2 on 2024-10-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_prompt_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='categories',
        ),
    ]
