# Generated by Django 5.1.2 on 2024-10-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_categories_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Prompt',
        ),
    ]
