# Generated by Django 5.1.2 on 2024-10-23 08:05

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_prompt_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='keyword',
            field=banjo.models.StringField(default=''),
        ),
    ]
